### ISSUE TITLE
What neuralcoref's version ?

### ISSUE THREAD

**Issue by aresa7796** [Dhyeythumar/Knowledge-Graph-with-Neo4j#1] opened 2021-05-10 02:07 UTC
Hi, I use neuralcoref;

```
$ git clone https://github.com/huggingface/neuralcoref.git
$ cd neuralcoref
$ pip install -r requirements.txt
$ pip install -e .
```

But,I get a error
```
 ERROR: Command errored out with exit status 1:
     command: /Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/neuralcoref/setup.py'"'"'; __file__='"'"'/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/neuralcoref/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/l8/ggzvv1b936xgcblr672ksp240000gn/T/pip-pip-egg-info-os020v2l
         cwd: /Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/neuralcoref/
    Complete output (37 lines):
    WARNING: The wheel package is not available.
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
    ERROR: No matching distribution found for wheel
    Traceback (most recent call last):
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/l8/ggzvv1b936xgcblr672ksp240000gn/T/tmp9fypuvx2', '--quiet', 'wheel']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/neuralcoref/setup.py", line 239, in <module>
        setup_package()
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/neuralcoref/setup.py", line 236, in setup_package
        cmdclass={"build_ext": build_ext_subclass})
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/setuptools/dist.py", line 751, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/setuptools/dist.py", line 807, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/l8/ggzvv1b936xgcblr672ksp240000gn/T/tmp9fypuvx2', '--quiet', 'wheel']' returned non-zero exit status 1.
    Cythonizing sources
    ----------------------------------------
WARNING: Discarding file:///Users/zhuzichun/work/demo/Knowledge-Graph-with-Neo4j/neuralcoref. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Can you help me? @Dhyeythumar

**Comment by dhyeythumar** [comment] 2021-05-10 03:15
Hi @aresa7796, This are the list of packages and their versions
```
Package         Version   Location
--------------- --------- -------------------------------------------------------
atomicwrites    1.4.0
attrs           21.2.0
beautifulsoup4  4.9.3
blis            0.4.1
boto3           1.17.69
botocore        1.20.69
catalogue       1.0.0
certifi         2020.12.5
chardet         3.0.4
colorama        0.4.4
cycler          0.10.0
cymem           2.0.5
Cython          0.29.23
decorator       5.0.7
dnspython       2.0.0
html2text       2020.1.16
html5lib        1.1
idna            2.10
iniconfig       1.1.1
jmespath        0.10.0
kiwisolver      1.3.1
matplotlib      3.3.2
murmurhash      1.0.5
neo4j-driver    4.1.1
neobolt         1.7.17
neomodel        4.0.1
networkx        2.5
neuralcoref     4.0       c:\users\dhyey\desktop\projects\KG_project\neuralcoref
numpy           1.20.2
packaging       20.9
pandas          1.1.4
Pillow          8.2.0
pip             21.1.1
plac            1.1.3
pluggy          0.13.1
preshed         3.0.5
py              1.10.0
pymongo         3.11.0
pyparsing       2.4.7
pytest          6.2.4
python-dateutil 2.8.1
pytz            2021.1
requests        2.24.0
s3transfer      0.4.2
setuptools      51.1.2
Shapely         1.7.1
six             1.16.0
soupsieve       2.2.1
spacy           2.3.2
srsly           1.0.5
thinc           7.4.1
toml            0.10.2
tqdm            4.60.0
urllib3         1.25.11
wasabi          0.8.2
webencodings    0.5.1
wheel           0.36.2
```

@aresa7796 Are you using the python 3.9? I think it is incompatible with the spacy (v2.3.2) library.
I am using the python 3.8.10 to create a virtual environment, I will modify the readme so that this version is only used to create the virtual envs.

You can do this by the below command (just make sure you install python 3.8.x)
```
virtualenv KG_env -p path/to/your/python/3.8/exe/file
```

**Comment by dhyeythumar** [comment] 2021-05-15 03:35
I hope the issue is resolved ✌🏻. I am closing this issue, but if you have any further more questions then you can reopen it.

**Closed as completed by dhyeythumar** 2021-05-15 03:35 UTC
